steps: 
  - 
    args: 
      - serverless
      - deploy
    env: 
      - 
        name: AWS_ACCESS_KEY_ID
        valueFrom: 
          secretKeyRef: 
            name: awscreds
            key: aws_access_key_id
      - 
        name: AWS_SECRET_ACCESS_KEY
        valueFrom: 
          secretKeyRef: 
            name: awscreds
            key: aws_secret_access_key
    image: gcr.io/triggermesh/serverless
    name: deploy
  

